apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  labels:
    app: nginx-test-app
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx-test-app
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
        - name: nginx
          image: yaredd/nginx-test-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-app-service
spec:
  selector:
    app: nginx-test-app
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test-app-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: wolf
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-test-appservice
              servicePort: 80
